# Generated by Django 5.2 on 2025-05-22 05:08

import gestion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_usuario_foto_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=gestion.models.ruta_foto_perfil),
        ),
    ]
