# Generated by Django 5.2 on 2025-05-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='prieba_git',
            field=models.CharField(blank=True, default='prueba', max_length=20, null=True),
        ),
    ]
