# Generated by Django 5.1.1 on 2025-05-22 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_usuario_prieba_git'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='prieba_git',
        ),
    ]
