# Generated by Django 5.1.1 on 2025-05-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_remove_usuario_prieba_git'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='anio_escolar',
            field=models.CharField(blank=True, choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero'), ('4', 'Cuarto')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='carrera',
            field=models.CharField(blank=True, choices=[('1', 'Ingenieria en Ciencias Informáticas'), ('2', 'Ciberseguridad'), ('3', 'Bioinformática'), ('4', 'Redes y Seguridad Informática')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('profesor', 'Profesor del Centro')], default='estudiante', max_length=20),
        ),
    ]
