# Generated by Django 5.1.7 on 2025-05-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_usuario_anio_escolar_alter_usuario_carrera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='descripcion',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='lugar',
            field=models.CharField(choices=[('Docente 1', 'Docente 1'), ('Docente 2', 'Docente 2'), ('Docente 3', 'Docente 3'), ('Docente 4', 'Docente 4'), ('Docente 5', 'Docente 5'), ('Docente 6', 'Docente 6')], max_length=100),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='tipo',
            field=models.CharField(choices=[('entrevista', 'Entrevista'), ('certificacion', 'Certificación'), ('curso', 'Curso'), ('colocacion', 'Colocación'), ('revalorizacion', 'Revalorización')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='anio_escolar',
            field=models.CharField(blank=True, choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero'), ('4', 'Cuarto')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='facultad',
            field=models.CharField(blank=True, choices=[('1', 'FTL'), ('2', 'FCS'), ('3', 'FIO'), ('4', 'FTI'), ('5', 'CITEC'), ('6', 'FTE')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='grupo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nivel',
            field=models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('profesor', 'Profesor del Centro')], max_length=20),
        ),
    ]
