# Generated by Django 5.2 on 2025-06-08 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("convocatorias", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inscripcion", models.DateField(auto_now_add=True)),
                (
                    "convocatoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="convocatorias.convocatoria",
                    ),
                ),
            ],
        ),
    ]
