# Generated by Django 5.2 on 2025-06-08 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inscripciones", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inscripcion",
            name="estudiante",
            field=models.ForeignKey(
                limit_choices_to={"tipo_usuario": "estudiante"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="inscripcion",
            constraint=models.UniqueConstraint(
                fields=("estudiante", "convocatoria"),
                name="unique_inscripcion_estudiante_convocatoria",
            ),
        ),
    ]
