# Generated by Django 5.2.1 on 2025-06-09 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
        ),
    ]
