# Generated by Django 5.1.1 on 2025-06-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='facultad',
            field=models.CharField(blank=True, choices=[('FTL', 'FTL'), ('FCS', 'FCS'), ('FIO', 'FIO'), ('FTI', 'FTI'), ('CITEC', 'CITEC'), ('FTE', 'FTE')], max_length=10, null=True),
        ),
    ]
