# Generated by Django 5.1.1 on 2025-06-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_facultad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='carrera',
            field=models.CharField(blank=True, choices=[('Ingenieria en Ciencias Informáticas', 'Ingenieria en Ciencias Informáticas'), ('Ciberseguridad', 'Ciberseguridad'), ('Bioinformática', 'Bioinformática'), ('Redes y Seguridad Informática', 'Redes y Seguridad Informática')], max_length=100, null=True),
        ),
    ]
