# Generated by Django 5.2 on 2025-06-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Convocatoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A1", "A1"),
                            ("A2", "A2"),
                            ("B1", "B1"),
                            ("B2", "B2"),
                            ("C1", "C1"),
                            ("C2", "C2"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("entrevista", "Entrevista"),
                            ("certificacion", "Certificación"),
                            ("curso", "Curso"),
                            ("colocacion", "Colocación"),
                            ("revalorizacion", "Revalorización"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descripcion", models.TextField(max_length=300)),
                (
                    "lugar",
                    models.CharField(
                        choices=[
                            ("Docente 1", "Docente 1"),
                            ("Docente 2", "Docente 2"),
                            ("Docente 3", "Docente 3"),
                            ("Docente 4", "Docente 4"),
                            ("Docente 5", "Docente 5"),
                            ("Docente 6", "Docente 6"),
                        ],
                        max_length=100,
                    ),
                ),
                ("fecha", models.DateField()),
                ("hora", models.TimeField()),
                ("estado", models.BooleanField(default=True)),
            ],
        ),
    ]
