# Generated by Django 5.1.1 on 2025-06-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
