# Generated by Django 5.1.1 on 2025-06-15 23:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0003_alter_convocatoria_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
