# Generated by Django 5.2 on 2025-06-08 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inscripciones", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resultado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nota",
                    models.CharField(
                        choices=[
                            ("A1", "A1"),
                            ("A2", "A2"),
                            ("B1", "B1"),
                            ("B2", "B2"),
                            ("C1", "C1"),
                            ("C2", "C2"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "inscripcion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inscripciones.inscripcion",
                    ),
                ),
            ],
        ),
    ]
