# Generated by Django 5.1.1 on 2025-06-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0002_resultado_notac_resultado_notal_resultado_notao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultado',
            name='notaR',
        ),
        migrations.AddField(
            model_name='resultado',
            name='notaE',
            field=models.CharField(blank=True, choices=[('', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='nota',
            field=models.CharField(blank=True, choices=[('', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='notaC',
            field=models.CharField(blank=True, choices=[('', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='notaL',
            field=models.CharField(blank=True, choices=[('', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='notaO',
            field=models.CharField(blank=True, choices=[('', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=10, null=True),
        ),
    ]
