# Generated by Django 5.1.1 on 2025-06-15 23:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0005_alter_resultado_nota_alter_resultado_notac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
