name: Unit Tests & Coverage
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.2
        env:
          POSTGRES_DB: test_db
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest coverage
      - name: Run tests with coverage
        env:
          DATABASE_URL: postgres://postgres:@postgres:5432/test_db
        run: |
          coverage run -m pytest app/tests/unit/
          coverage xml
      - name: Upload coverage report
        uses: codecov/codecov-action@v3
